# Generated by Django 4.1 on 2022-08-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
